name: munatasks2
description: MunaTasks versão 2.0.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.3.3+4

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  local_auth: ^1.1.8
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.2
  mobx: ^2.0.7+2
  flutter_mobx: ^2.0.6+1
  build_runner: ^2.1.10
  path_provider: ^2.0.10
  hive: ^2.1.0
  shared_preferences: ^2.0.15
  google_fonts: ^2.1.1
  image_picker: ^0.8.5+3
  freezed_annotation: ^1.1.0
  layout: ^1.0.2
  http: ^0.13.4
  rolling_switch: ^0.0.2
  simple_animations: ^4.0.1
  supercharged: ^2.1.1
  accordion: ^2.1.2
  badges: ^2.0.2
  google_sign_in: ^5.3.0
  flutter_zoom_drawer: ^2.1.2
  flutter_iconpicker: ^3.1.4+1
  bubble_bottom_bar: ^2.0.0
  boardview: ^0.2.2
  intl: ^0.17.0
  date_format: ^2.0.5
  flutter_folding_card: ^1.0.0+1
  dio: ^4.0.6
  dwds: ^13.1.0
  file_picker: ^4.5.1
  flutter_session_manager: ^1.0.3
  crypto: ^3.0.2
  universal_html: ^2.0.8
  flutter_local_notifications: ^9.5.2
  show_update_dialog: ^1.0.10
  package_info_plus: ^1.0.6
  responsive_framework: ^0.2.0
  cached_network_image: ^3.2.1
  auto_size_text: ^3.0.0
  bitsdojo_window: ^0.1.2
  url_launcher: ^6.1.2
  socket_io_client: ^1.0.2
  image_cropper: ^2.0.3
  image_cropper_view: ^0.0.2
  collapsible_sidebar: ^2.0.1+2
  sidebarx: ^0.5.0
  getwidget: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.6+2
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  color: "#f7f6f4"
  image: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/exe/
    - assets/img/
    - assets/icon/icon.png

scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs
  chrome: flutter run -d Chrome --dart-define=FLUTTER_WEB_CANVASKIT_FORCE_CPU_ONLY=true --release --web-port 52230
  build_web: flutter build web --web-renderer canvaskit --release && scp -r .\build\web\* root@45.82.75.3:/home/munatask/public_html/
  build_windows: flutter build windows
  build_linux: flutter build linux
  snapcraft: snapcraft
  snapcraft_upload: snapcraft upload --release=stable munatask_2.3.3_amd64.snap
  build_bundle: flutter build appbundle --build-name=2.3.3 --build-number=233 --no-tree-shake-icons
  build_apk: flutter build apk --build-name=2.1.5+5 --build-number=215 --no-tree-shake-icons
  launch_icon: flutter pub run flutter_launcher_icons:main
  launch_splash: flutter pub run flutter_native_splash:create
