name: munatasks2
description: MunaTasks versão 2.0.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3+8

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  local_auth: ^1.1.8
  cloud_firestore: ^3.1.0
  firebase_storage: ^10.1.0
  firebase_auth: ^3.1.4
  firebase_core: ^1.12.0
  cupertino_icons: ^1.0.2
  flutter_modular: ^4.4.0
  firebase_dynamic_links: ^3.0.2
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  build_runner: ^2.1.5
  path_provider:
  hive: ^2.0.5
  shared_preferences:
  google_fonts: ^2.0.0
  image_picker: ^0.8.4+4
  freezed_annotation: ^1.1.0
  google_sign_in: ^5.2.0
  layout: ^1.0.2
  http: ^0.13.4
  rolling_switch: ^0.0.2
  simple_animations: ^4.0.1
  supercharged: ^2.1.1
  accordion: ^2.1.2
  badges: ^2.0.2
  flutter_zoom_drawer: ^2.1.2
  flutter_iconpicker: ^3.1.2
  bubble_bottom_bar: ^2.0.0
  boardview: ^0.2.2
  intl: ^0.17.0
  date_format: ^2.0.5
  cloud_functions: ^3.2.6
  flutter_folding_card: ^1.0.0+1
  dio: ^4.0.4
  objectid: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.4
  freezed: ^1.1.0
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  color: "#f7f6f4"
  image: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/icon/icon.png

scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs
  chrome: flutter run -d chrome --web-renderer html --web-port 52230
  build_bundle: flutter build appbundle --build-name=1.1.6+4 --build-number=13 --no-tree-shake-icons
  build_web: flutter build web --web-renderer html --release && firebase deploy
  build_apk: flutter build apk
  launch_icon: flutter pub run flutter_launcher_icons:main
  launch_splash: flutter pub run flutter_native_splash:create
  functions: firebase deploy --only functions
  simulador_functions: firebase emulators:start --only functions
