name: munatask
version: 2.3.2
summary: Munatask kanban
description: Kanban para controller de tarefas
confinement: strict
base: core18
grade: stable
icon: snap/gui/icon.png

apps:
  munatask:
    command: munatask
    extensions: [flutter-master]
    plugs:
      - network
      - desktop

parts:
  munatask:
    source: build/linux/x64/release/bundle
    plugin: flutter
    flutter-target: lib/main.dart
    stage:
      - -usr/bin/flutter
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/libexec
      cp -r $SNAPCRAFT_PART_SRC $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $SNAPCRAFT_PART_INSTALL/usr/bin/flutter
